### STAGES ###
stages:
  - test
  - build
  - review
  - deploy
  - release

### GLOBAL VARS ###
variables:
  IMAGE_NAME: registry.gitlab.com/${CI_PROJECT_PATH}
  IMAGE_NAME_COMMIT: registry.gitlab.com/${CI_PROJECT_PATH}/commits/${CI_PROJECT_NAME}:${CI_BUILD_REF}
  NGINX_NAME: registry.gitlab.com/${CI_PROJECT_PATH}/nginx/${CI_PROJECT_NAME}-nginx
  NGINX_NAME_COMMIT: registry.gitlab.com/${CI_PROJECT_PATH}/nginx-commits/${CI_PROJECT_NAME}-nginx:${CI_BUILD_REF}
  DOCKER_DRIVER: overlay2

### TEST STAGE ###
py36:
  stage: test
  image: registry.gitlab.com/cloudigrade/images/build-container:latest
  before_script:
    - pip install tox codecov
  script:
    - tox -e py36
    - codecov

flake8:
  stage: test
  image: registry.gitlab.com/cloudigrade/images/build-container:latest
  before_script:
    - pip install tox
  script: tox -e flake8

Cloudigrade Docker:
  stage: test
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker pull ${IMAGE_NAME}:latest || true
    - docker build --cache-from ${IMAGE_NAME}:latest .

NGINX S2i:
  stage: test
  image: docker:stable
  services:
    - docker:dind
  variables:
    CONTEXT_DIR: deployment/prod/
    NGINX_S2I_IMAGE: centos/nginx-112-centos7:latest
    S2I_VERSION: v1.1.10
    S2I_RELEASE: source-to-image-v1.1.10-27f0729d-linux-amd64
  before_script:
    - apk --no-cache add git
    - mkdir /opt && cd /opt
    - wget https://github.com/openshift/source-to-image/releases/download/${S2I_VERSION}/${S2I_RELEASE}.tar.gz -O /opt/s2i.tar.gz
    - tar --strip-components=1 -xzvf /opt/s2i.tar.gz -C /opt/
    - mv /opt/s2i /usr/bin/
  script:
    - s2i build --context-dir=${CONTEXT_DIR} --ref ${CI_COMMIT_REF_NAME} ${CI_PROJECT_URL} ${NGINX_S2I_IMAGE} ${IMAGE_NAME}:latest

### BUILD STAGE ###
Push Cloudigrade Image:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  only:
    - master@cloudigrade/cloudigrade
  except:
    - tags@cloudigrade/cloudigrade
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker pull ${IMAGE_NAME}:latest || true
    - docker build --cache-from ${IMAGE_NAME}:latest --tag ${IMAGE_NAME_COMMIT} --tag ${IMAGE_NAME}:latest .
    - docker push ${IMAGE_NAME_COMMIT}
    - docker push ${IMAGE_NAME}:latest

Push Cloudigrade Tagged Image:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  only:
    - tags@cloudigrade/cloudigrade
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - docker pull ${IMAGE_NAME}:latest || true
    - docker build --cache-from ${IMAGE_NAME}:latest --tag ${IMAGE_NAME}:${CI_COMMIT_TAG} .
    - docker push ${IMAGE_NAME}:${CI_COMMIT_TAG}

Push NGINX Image:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  only:
    - master@cloudigrade/cloudigrade
  except:
    - tags@cloudigrade/cloudigrade
  variables:
    CONTEXT_DIR: deployment/prod/
    NGINX_S2I_IMAGE: centos/nginx-112-centos7:latest
    S2I_VERSION: v1.1.10
    S2I_RELEASE: source-to-image-v1.1.10-27f0729d-linux-amd64
  before_script:
    - apk --no-cache add git
    - mkdir /opt && cd /opt
    - wget https://github.com/openshift/source-to-image/releases/download/${S2I_VERSION}/${S2I_RELEASE}.tar.gz -O /opt/s2i.tar.gz
    - tar --strip-components=1 -xzvf /opt/s2i.tar.gz -C /opt/
    - mv /opt/s2i /usr/bin/
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - s2i build --context-dir=${CONTEXT_DIR} ${CI_PROJECT_URL} ${NGINX_S2I_IMAGE} ${NGINX_NAME_COMMIT}
    - docker tag ${NGINX_NAME_COMMIT} ${NGINX_NAME}:latest
    - docker push ${NGINX_NAME_COMMIT}
    - docker push ${NGINX_NAME}:latest

Push NGINX Tagged Image:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  only:
    - tags@cloudigrade/cloudigrade
  variables:
    CONTEXT_DIR: deployment/prod/
    NGINX_S2I_IMAGE: centos/nginx-112-centos7:latest
    S2I_VERSION: v1.1.10
    S2I_RELEASE: source-to-image-v1.1.10-27f0729d-linux-amd64
  before_script:
    - apk --no-cache add git
    - mkdir /opt && cd /opt
    - wget https://github.com/openshift/source-to-image/releases/download/${S2I_VERSION}/${S2I_RELEASE}.tar.gz -O /opt/s2i.tar.gz
    - tar --strip-components=1 -xzvf /opt/s2i.tar.gz -C /opt/
    - mv /opt/s2i /usr/bin/
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
  script:
    - s2i build --context-dir=${CONTEXT_DIR} ${CI_PROJECT_URL} ${NGINX_S2I_IMAGE} ${NGINX_NAME}:${CI_COMMIT_TAG}
    - docker push ${NGINX_NAME}:${CI_COMMIT_TAG}

### REVIEW STAGE ###
Deploy-Review:
  stage: review
  image: registry.gitlab.com/cloudigrade/images/deploy-container:latest
  variables:
    GIT_STRATEGY: none
  only:
    - branches@cloudigrade/cloudigrade
    - chat
  except:
    - master@cloudigrade/cloudigrade
    - tags@cloudigrade/cloudigrade
  before_script:
    - oc login --token ${KUBE_TOKEN}
    - git clone https://gitlab.com/cloudigrade/shiftigrade.git
    - cd shiftigrade
  script:
    - >
      ansible-playbook \
        -e application_name=houndigrade \
        -e aws_prefix="${CI_COMMIT_REF_SLUG}" \
        -e ec2_ami_id="${RECOMMENDED_AMI}" \
        -e ec2_asg_availability_zones="${HOUNDIGRADE_AWS_AVAILABILITY_ZONE}" \
        -e ec2_asg_desired_capacity=0 \
        -e ec2_asg_max_size=0 \
        -e ec2_asg_min_size=0 \
        -e ec2_asg_name="${HOUNDIGRADE_AWS_AUTOSCALING_GROUP_NAME}" \
        -e ec2_asg_vpc_subnets="${SUBNET_NAME}" \
        -e ec2_instance_name="${EC2_HOST_NAME}" \
        -e ec2_instance_type="${INSTANCE_TYPE}" \
        -e ec2_launch_configuration_name="${HOUNDIGRADE_LAUNCH_CONFIG_NAME}" \
        -e ec2_security_groups="${SECURITY_GROUP_NAME}" \
        -e ecs_cluster_name="${HOUNDIGRADE_ECS_CLUSTER_NAME}" \
        -e key_name="${SSH_KEY_NAME}" \
        -e vpc_name="${VPC_NAME}" \
        -e bucket_name="${AWS_S3_BUCKET_NAME}" \
        ansible/provision-aws-resources.yaml
    - >
      if ! oc rollout status dc/cloudireview-${CI_COMMIT_REF_SLUG}-db; then
        oc process openshift//postgresql-ephemeral \
          -p DATABASE_SERVICE_NAME=cloudireview-${CI_COMMIT_REF_SLUG}-db \
          -p POSTGRESQL_DATABASE=postgres \
          -p POSTGRESQL_VERSION=9.6 \
          -l app=${CI_COMMIT_REF_SLUG} \
        | oc apply -f - && \
        oc rollout status dc/cloudireview-${CI_COMMIT_REF_SLUG}-db;
      else
        echo "${CI_COMMIT_REF_SLUG}-db already exists, keeping."
      fi
    - kontemplate template ocp/review.yaml -i cloudigrade | oc apply -f -
    - oc start-build -F cloudireview-${CI_COMMIT_REF_SLUG}-cloudigrade-api
    - oc start-build -F cloudireview-${CI_COMMIT_REF_SLUG}-cloudigrade-nginx
    - if ! oc rollout status dc/cloudireview-${CI_COMMIT_REF_SLUG}-cloudigrade-api; then oc rollout latest dc/cloudireview-${CI_COMMIT_REF_SLUG}-cloudigrade-api && oc rollout status dc/cloudireview-${CI_COMMIT_REF_SLUG}-cloudigrade-api; fi;
    - if ! oc rollout status dc/cloudireview-${CI_COMMIT_REF_SLUG}-cloudigrade-celery-beat; then oc rollout latest dc/cloudireview-${CI_COMMIT_REF_SLUG}-cloudigrade-celery-beat && oc rollout status dc/cloudireview-${CI_COMMIT_REF_SLUG}-cloudigrade-celery-beat; fi;
    - if ! oc rollout status dc/cloudireview-${CI_COMMIT_REF_SLUG}-cloudigrade-celery-worker; then oc rollout latest dc/cloudireview-${CI_COMMIT_REF_SLUG}-cloudigrade-celery-worker && oc rollout status dc/cloudireview-${CI_COMMIT_REF_SLUG}-cloudigrade-celery-worker; fi;
  environment:
    name: review/${CI_COMMIT_REF_NAME}
    url: https://cloudireview-${CI_COMMIT_REF_SLUG}.1b13.insights.openshiftapps.com
    on_stop: Clean-Up-Review

Clean-Up-Review:
  stage: review
  image: registry.gitlab.com/cloudigrade/images/deploy-container:latest
  variables:
    GIT_STRATEGY: none
    HOUNDIGRADE_AWS_AUTOSCALING_GROUP_NAME: ${CI_COMMIT_REF_SLUG}-houndigrade-asg
    HOUNDIGRADE_ECS_CLUSTER_NAME: ${CI_COMMIT_REF_SLUG}-houndigrade
    HOUNDIGRADE_LAUNCH_CONFIG_NAME: ${CI_COMMIT_REF_SLUG}-houndigrade-lc
  only:
    - branches@cloudigrade/cloudigrade
    - chat
  except:
    - master@cloudigrade/cloudigrade
    - tags@cloudigrade/cloudigrade
  before_script:
    - oc login ${OPENSHIFT_URL} --token ${KUBE_TOKEN}
    - git clone https://gitlab.com/cloudigrade/shiftigrade.git
    - cd shiftigrade
  script:
    - oc delete bc,cm,dc,is,routes,secrets,svc -l gitlab-deployment="${CI_COMMIT_REF_SLUG}-cloudigrade"
    - oc delete dc,svc,secret "cloudireview-${CI_COMMIT_REF_SLUG}-db"
    - >
      ansible-playbook \
        -e aws_prefix="${CI_COMMIT_REF_SLUG}" \
        -e bucket_state=absent \
        -e ec2_asg_name="${HOUNDIGRADE_AWS_AUTOSCALING_GROUP_NAME}" \
        -e ec2_asg_state=absent \
        -e ec2_launch_configuration_name="${HOUNDIGRADE_LAUNCH_CONFIG_NAME}" \
        -e ec2_lc_state=absent \
        -e ecs_cluster_name="${HOUNDIGRADE_ECS_CLUSTER_NAME}" \
        -e ecs_state=absent \
        -e sqs_state=absent \
        ansible/provision-aws-resources.yaml
    - ansible-playbook -e aws_prefix="${CI_COMMIT_REF_SLUG}" -e sqs_state=absent ansible/clean-sqs.yaml
  when: manual
  environment:
    name: review/${CI_COMMIT_REF_NAME}
    action: stop

### DEPLOY STAGE ###
### MASTER ONLY ###
Deploy to Test:
  stage: deploy
  image: registry.gitlab.com/cloudigrade/images/deploy-container:latest
  variables:
    GIT_STRATEGY: none
    API_IMAGE: registry.gitlab.com/${CI_PROJECT_PATH}/commits/${CI_PROJECT_NAME}:${CI_BUILD_REF}
    NGINX_IMAGE: registry.gitlab.com/${CI_PROJECT_PATH}/nginx-commits/${CI_PROJECT_NAME}-nginx:${CI_BUILD_REF}
    CELERY_IMAGE: registry.gitlab.com/${CI_PROJECT_PATH}/commits/${CI_PROJECT_NAME}:${CI_BUILD_REF}
  only:
    - master@cloudigrade/cloudigrade
  before_script:
    - oc login --token ${KUBE_TOKEN}
    - git clone https://gitlab.com/cloudigrade/shiftigrade.git
    - cd shiftigrade
  script:
    - kontemplate template ocp/test.yaml -i cloudigrade | oc apply -f -
    - if ! oc rollout status dc/cloudigrade-api; then oc rollout latest dc/cloudigrade-api && oc rollout status dc/cloudigrade-api; fi;
    - if ! oc rollout status dc/cloudigrade-celery-beat; then oc rollout latest dc/cloudigrade-celery-beat && oc rollout status dc/cloudigrade-celery-beat; fi;
    - if ! oc rollout status dc/cloudigrade-celery-worker; then oc rollout latest dc/cloudigrade-celery-worker && oc rollout status dc/cloudigrade-celery-worker; fi;
  environment:
    name: test
    url: https://test.cloudigra.de/

Deploy to Stage:
  stage: deploy
  image: registry.gitlab.com/cloudigrade/images/deploy-container:latest
  variables:
    GIT_STRATEGY: none
    API_IMAGE: registry.gitlab.com/${CI_PROJECT_PATH}:${CI_COMMIT_TAG}
    NGINX_IMAGE: registry.gitlab.com/${CI_PROJECT_PATH}/nginx/${CI_PROJECT_NAME}-nginx:${CI_COMMIT_TAG}
    CELERY_IMAGE: registry.gitlab.com/${CI_PROJECT_PATH}:${CI_COMMIT_TAG}
  only:
    - tags@cloudigrade/cloudigrade
  before_script:
    - oc login --token ${KUBE_TOKEN}
    - git clone https://gitlab.com/cloudigrade/shiftigrade.git
    - cd shiftigrade
  script:
    - kontemplate template ocp/stage.yaml -i cloudigrade | oc apply -f -
    - if ! oc rollout status dc/cloudigrade-api; then oc rollout latest dc/cloudigrade-api && oc rollout status dc/cloudigrade-api; fi;
    - if ! oc rollout status dc/cloudigrade-celery-beat; then oc rollout latest dc/cloudigrade-celery-beat && oc rollout status dc/cloudigrade-celery-beat; fi;
    - if ! oc rollout status dc/cloudigrade-celery-worker; then oc rollout latest dc/cloudigrade-celery-worker && oc rollout status dc/cloudigrade-celery-worker; fi;
  environment:
    name: stage
    url: https://stage.cloudigra.de/

### RELEASE STAGE ###
Deploy to Production:
  stage: release
  image: registry.gitlab.com/cloudigrade/images/deploy-container:latest
  variables:
    GIT_STRATEGY: none
    API_IMAGE: registry.gitlab.com/${CI_PROJECT_PATH}:${CI_COMMIT_TAG}
    NGINX_IMAGE: registry.gitlab.com/${CI_PROJECT_PATH}/nginx/${CI_PROJECT_NAME}-nginx:${CI_COMMIT_TAG}
    CELERY_IMAGE: registry.gitlab.com/${CI_PROJECT_PATH}:${CI_COMMIT_TAG}
  only:
    - tags@cloudigrade/cloudigrade
  before_script:
    - oc login --token ${KUBE_TOKEN}
    - git clone https://gitlab.com/cloudigrade/shiftigrade.git
    - cd shiftigrade
  script:
    - kontemplate template ocp/prod.yaml -i cloudigrade | oc apply -f -
    - if ! oc rollout status dc/cloudigrade-api; then oc rollout latest dc/cloudigrade-api && oc rollout status dc/cloudigrade-api; fi;
    - if ! oc rollout status dc/cloudigrade-celery-beat; then oc rollout latest dc/cloudigrade-celery-beat && oc rollout status dc/cloudigrade-celery-beat; fi;
    - if ! oc rollout status dc/cloudigrade-celery-worker; then oc rollout latest dc/cloudigrade-celery-worker && oc rollout status dc/cloudigrade-celery-worker; fi;
  when: manual
  environment:
    name: production
    url: https://www.cloudigra.de/
